# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedSyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
            ],
        ),
    ]
